// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Management_System_MVC__EF.Data;

#nullable disable

namespace Student_Management_System_MVC__EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309164126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student_Management_System_MVC__EF.Models.Mark", b =>
                {
                    b.Property<int>("MarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkId"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkId");

                    b.HasIndex("StudentId");

                    b.ToTable("Marks");

                    b.HasData(
                        new
                        {
                            MarkId = 1,
                            Score = 90,
                            StudentId = 1,
                            Subject = "Maths"
                        },
                        new
                        {
                            MarkId = 2,
                            Score = 85,
                            StudentId = 1,
                            Subject = "Physics"
                        },
                        new
                        {
                            MarkId = 3,
                            Score = 80,
                            StudentId = 2,
                            Subject = "Chemistry"
                        });
                });

            modelBuilder.Entity("Student_Management_System_MVC__EF.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rahul@gmail.com",
                            Name = "Rahul",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "aman@gmail.com",
                            Name = "Aman",
                            Password = "456"
                        });
                });

            modelBuilder.Entity("Student_Management_System_MVC__EF.Models.Mark", b =>
                {
                    b.HasOne("Student_Management_System_MVC__EF.Models.Student", "student")
                        .WithMany("marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("Student_Management_System_MVC__EF.Models.Student", b =>
                {
                    b.Navigation("marks");
                });
#pragma warning restore 612, 618
        }
    }
}
