// <auto-generated />
using Library_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307065841_DataTypeChange")]
    partial class DataTypeChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library_Management_System.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("BookPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookName = "CSharp",
                            BookPrice = 500.0
                        },
                        new
                        {
                            Id = 2,
                            BookName = "DotNet",
                            BookPrice = 650.0
                        },
                        new
                        {
                            Id = 3,
                            BookName = "MVC",
                            BookPrice = 700.0
                        },
                        new
                        {
                            Id = 4,
                            BookName = "Java",
                            BookPrice = 550.0
                        },
                        new
                        {
                            Id = 5,
                            BookName = "Python",
                            BookPrice = 600.0
                        },
                        new
                        {
                            Id = 6,
                            BookName = "JavaScript",
                            BookPrice = 450.0
                        },
                        new
                        {
                            Id = 7,
                            BookName = "Angular",
                            BookPrice = 750.0
                        },
                        new
                        {
                            Id = 8,
                            BookName = "React",
                            BookPrice = 800.0
                        },
                        new
                        {
                            Id = 9,
                            BookName = "NodeJS",
                            BookPrice = 720.0
                        },
                        new
                        {
                            Id = 10,
                            BookName = "SQLServer",
                            BookPrice = 680.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
